-- Perennial Home & Gardens — Garden Library Phase 9
-- Prepared schema for future Supabase account sync. Not active until a Perennial Supabase project is created.
create table if not exists public.garden_library_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  home_zone text,
  location_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.garden_library_saved_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null check (item_type in ('plant','term','resource')),
  item_key text not null,
  collection_name text not null default 'favorites',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,item_type,item_key,collection_name)
);

alter table public.garden_library_profiles enable row level security;
alter table public.garden_library_saved_items enable row level security;

drop policy if exists "Users manage own garden library profile" on public.garden_library_profiles;
create policy "Users manage own garden library profile"
on public.garden_library_profiles for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own garden library items" on public.garden_library_saved_items;
create policy "Users manage own garden library items"
on public.garden_library_saved_items for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists garden_library_saved_items_user_idx
on public.garden_library_saved_items(user_id,item_type);
